name: CI
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'
      - '**/.gitkeep'
      - '**/*.example'
      - '.vscode'

jobs:
  # Build
  build:
    name: Build
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn
      - run: yarn build

  # Publish docker image
  publish:
    needs: [build]
    name: Publish docker image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKER_USERNAME }}/histories
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest, 0.${{ github.run_number }}'

  # Create comment on commit
  comment:
    name: Comment docker tag
    needs: [publish]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v3
      - name: Add commit comment
        run: |
          jq -nc '{"body": "Docker image automatically deployed🥳 `docker pull ${{ secrets.DOCKER_USERNAME }}/histories-backend:0.${{ github.run_number }}`"}' | \
          curl -sL  -X POST -d @- \
            -H "Content-Type: application/json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/comments"
